# Generated by Django 4.1.6 on 2023-02-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_price',
            old_name='cust_term_prod_id',
            new_name='cust_term_prod',
        ),
    ]
