# Generated by Django 4.1.6 on 2023-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_terminal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dtn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='terminal_customer_mapping',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
