# Generated by Django 4.1.6 on 2023-02-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_dtn_alter_terminal_customer_mapping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_price',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
