# Generated by Django 4.1.6 on 2023-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location_price_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='dtn_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
