# Generated by Django 4.1.6 on 2023-02-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dtn_load'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtn_load',
            old_name='load',
            new_name='loadno',
        ),
    ]
