# Generated by Django 4.1.6 on 2023-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_load_dtn_load_loadno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_price',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
