# Generated by Django 4.1.6 on 2023-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cust_price_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='dtn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
