# Generated by Django 4.1.6 on 2023-03-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_useraccess_alter_customer_dtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtn_load',
            name='day_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='email_trigger',
            field=models.BooleanField(default=True),
        ),
    ]
