# Generated by Django 4.1.6 on 2023-03-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_myfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myfile',
            unique_together={('name', 'version', 'created_at')},
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
