# Generated by Django 4.1.6 on 2023-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_myfile_unique_together_alter_myfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='day_id',
            field=models.IntegerField(default=0),
        ),
    ]
