# Generated by Django 4.1.6 on 2023-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_myfile_day_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='day_id',
            field=models.IntegerField(),
        ),
    ]
