# Generated by Django 4.1.6 on 2023-03-17 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cust_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_price',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
