# Generated by Django 4.1.6 on 2023-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_location_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='send_format',
            field=models.IntegerField(default=0),
        ),
    ]
