# Generated by Django 4.1.6 on 2023-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_send_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_price',
            name='base_price',
            field=models.FloatField(default=0),
        ),
    ]
