# Generated by Django 4.1.6 on 2023-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cust_price_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='metainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
