# Generated by Django 4.1.6 on 2023-04-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_metainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
