# Generated by Django 4.1.6 on 2023-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_customer_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mail',
        ),
        migrations.AddField(
            model_name='customer',
            name='mail_list_bcc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mail_list_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
