# Generated by Django 4.1.6 on 2023-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='location_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
