# Generated by Django 4.1.6 on 2023-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cust_price_sap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_price',
            name='sap',
        ),
        migrations.AddField(
            model_name='customer',
            name='sap',
            field=models.BooleanField(default=False),
        ),
    ]
