# Generated by Django 4.1.6 on 2023-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_terminal_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='rack',
        ),
        migrations.AddField(
            model_name='terminal_customer_mapping',
            name='rack',
            field=models.BooleanField(default=False),
        ),
    ]
